# -*- coding: utf-8 -*-
"""Practical_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OmuS4jX8lzJF3htuJAwoPmgQPDhVAiH
"""

import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
dataset = pd.read_csv("/content/drive/MyDrive/23012531032_ML_practical/dataset/zoo (1).csv")
dataset

dataset.shape

dataset.head(4)

dataset.tail(4)

dataset1 = pd.DataFrame([['kangaroo','veg'],['lion','meat'],['cheetah','meat']],columns=['animal','veg'])
dataset1

d = pd.merge(dataset1,dataset)
d

dataset.merge(dataset1,how='outer')

dataset.merge(dataset1,how='left')

dataset.merge(dataset1,how='right')

dataset.sort_values('animal')

dataset.sort_values('animal',ascending=False).reset_index()

dataset.sort_values('animal',ignore_index=1)

dataset.merge(dataset1,how='outer').fillna("N/A")

data = pd.read_excel("/content/drive/MyDrive/23012531032_ML_practical/dataset/Covid cases in India (1).xlsx")
data

data.describe()

data.info()

data.head()

data.tail()

data.columns

data.columns[1:3]

data.shape

data

data['TotalConfirmedCases']

newdata = data.iloc[1:3,1:3]
newdata

newdata=data[11:21].reset_index(drop = True)
newdata

a =  data[data['Active']>500].reset_index(drop = True)
a[['Name of State / UT','Active']]

b = data[(data['Active']>500)&(data['Deaths']>100)][['Name of State / UT','Active','Deaths']]
b

data1 =  data.groupby('Name of State / UT')['Deaths'].sum().sort_values(ascending=False).head(5)
data1

data.groupby('Name of State / UT')['Deaths'].sum().sort_values().head(5)

data.dropna()

data['Active'] = data['Active'].fillna(data['Active'].mean())
data['Recovered'] = data['Recovered'].fillna(data['Recovered'].mean())
data['Deaths'] = data['Deaths'].fillna(data['Deaths'].mean())

data['Active'] = data['Active'].fillna(data['Active'].median())
data['Recovered'] = data['Recovered'].fillna(data['Recovered'].median())
data['Deaths'] = data['Deaths'].fillna(data['Deaths'].median())

data['Active'] = data['Active'].fillna(data['Active'].mode()[0])
data['Recovered'] = data['Recovered'].fillna(data['Recovered'].mode()[0])
data['Deaths'] = data['Deaths'].fillna(data['Deaths'].mode()[0])

data

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,6))
data.plot(kind='bar', color='red')
plt.title(" States with Highest Deaths")
plt.xlabel("State")
plt.ylabel("Total Deaths")
plt.xticks(rotation=95)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))
plt.bar(data['Name of State / UT'], data['Active'], color='skyblue')
plt.xlabel("Name of State / UT")
plt.ylabel("Active Cases")
plt.title("Active COVID-19 Cases by State/UT")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()